version: '3'
services:
    scheduler:
        build: .
        image: video-to-blog-service
        volumes:
            - ~/.aws/:/root/.aws:ro
        environment:
            - userId=myUserId
            - videoUrl=https://www.youtube.com/watch?v=4bjDrOleJgI&ab_channel=DailyDoseOfInternet
            - videoUrlHash=asdfasdf
